### ISSUE TITLE
Website Stewardship

### ISSUE THREAD

**Issue by PullJosh** [PullJosh/leopard-website#40]
> cc @towerofnix, @adroitwhiz, @sfederici, @HanClinto, etc because I want your feedback and I suspect that you are not subscribed to this repo.

I am just about ready to share a hosted super-duper-alpha version of the [Scratch-style code editor](https://github.com/PullJosh/leopard-website/issues/38) for community feedback. I'm really excited about it! But expanding the scope of the website has also got me thinking a little bit about the new responsibilities that such an expansion will create, and I want to make sure we're all on the same page about those.

This is important to me because the website is a hosted, centralized *thing*, which doesn't lend itself to the same free-for-all contributions that our open source libraries do. Unlike `leopard` and `sb-edit`, the website has some centralized responsibilities:
- Expenses (domain, hosting, database, and with the new editor also uploaded assets)
- Legal liabilities (terms of service, COPPA, etc.)
- Moderation responsibility (social sharing will be extremely limited, at least at first, but there's still a lot of due diligence required when you allow users to upload arbitrary assets)

I am more than happy to be personally on the hook for paying all the website expenses, upholding legal responsibilities, etc. But I've realized that–unlike the open-source libraries, where I want to be a contributor/community member that is equal to everyone else–I only feel comfortable putting myself on the hook for the website management if we all are on board with me also having the final say on matters of website decision-making.

So here's my proposal for how I think things should be organized. **This isn't any different than how things have already been.** I just want to be completely clear and make sure we're all on the same page before the website begins to take a larger role in the Leopard ecosystem.

1. The `leopard` and `sb-edit` packages are fully community-driven. The process of designing and implementing new features & publishing new releases is as decentralized and democratic as we can practically achieve.
2. The `leopard-website` is community-inspired, but the responsibility for managing it falls on my shoulders. I pay the expenses, I own the website, any issues are directed at me. I will gladly incorporate ideas and contributions from others (more community is better!), but because all the liability is mine, I also get the final say in website-related decision making.

Again, this isn't really any different than what we've been doing so far. But I think now is the appropriate time to clarify the roles and responsibilities so that there isn't any confusion down the line.

I am incredibly grateful to everyone here who contributes to Leopard in big ways and small, and I want to make sure I'm doing right by you. The two bullet points above outline a community structure that feels healthiest to me, and that makes me feel safe taking on the website responsibilities with the new editor. But I want your feedback. Does this seem reasonable? Are there alternative structures that you believe would be more fair or lead to a better future for Leopard?

Thanks,
Josh

**Comment by HanClinto** [comment]
> 1. The leopard and sb-edit packages are fully community-driven. The process of designing and implementing new features & publishing new releases is as decentralized and democratic as we can practically achieve.
> 2. The leopard-website is community-inspired, but the responsibility for managing it falls on my shoulders. I pay the expenses, I own the website, any issues are directed at me. I will gladly incorporate ideas and contributions from others (more community is better!), but because all the liability is mine, I also get the final say in website-related decision making.
> 
> Again, this isn't really any different than what we've been doing so far. But I think now is the appropriate time to clarify the roles and responsibilities so that there isn't any confusion down the line.

This feels supremely reasonable to me. I'm a big fan of benevolent dictatorships in projects of this size, and I think there is a lot of wisdom in the way that you've laid it out here.

> Moderation responsibility (social sharing will be extremely limited, at least at first, but there's still a lot of due diligence required when you allow users to upload arbitrary assets)

This would be one of the exceptions -- I would hope that you wouldn't expect this to land solely on your shoulders? Moderation is a big lift, and -- similar to Reddit -- I think that unpaid community moderators can be a very valuable asset. Just like Reddit mods (generally) understand that they serve at the behest of the larger website, you would be the "super-moderator", but I would hope that you would employ the community helpers to moderate the website. 

Similarly, I don't want to see you take so much that you burn out -- just because final authority rests entirely with you (and everyone understands that), you should make it easy for people to support you. I'm imagining something like a Patreon to help defer recurring expenses would be something that people who are superfans -- fans of your work, your tools, your community -- these superfans can still support you and help you not be at such risk of burnout, and provide a base so that it could be more smoothly transferred when / if you wanted to shift its responsibility to someone else. 

I'm definitely not thinking of a "foundation" or anything like that -- I think it's wisest if you hold all the keys. That's why I like Patreon more that other things -- if people donate money, it's clearly a donation / support of an artist, and it might let you get a louder voice when making community votes, but it doesn't purchase an ownership stake. Ownership rests 100% with you, and I very much believe that's the best way to go forward.

**Comment by PullJosh** [comment]
> This feels supremely reasonable to me. I'm a big fan of benevolent dictatorships in projects of this size

Glad to hear it. My gut instinct was to think the same thing, but I'm glad to get some outside feedback before just assuming that "I should be benevolent dictator" is a good system for all of us.

> I would hope that you wouldn't expect [moderation] to land solely on your shoulders?

Agreed. I definitely don't have what it takes to be available 24/7, nor do I think that's a good idea for anybody involved.

In the short-term, I am hoping to avoid the issue as much as possible by limiting the social sharing features of the site. (As a bonus, limiting social features also helps keep the Scratch team happy. They are strict about linking out to sites with any social features, which is definitely something to navigate. Somehow Snap! seems to get by.)

My current intention is that users can "share" their projects, but when they do, absolutely nothing happens other than that they can now send the URL to a friend who can view it that way. So projects are public, but only if you know the URL, and there's no discovery built into the website. That might change eventually, but for now that should keep most moderation woes at bay. I would still want to block illegal & sexual content, but with the help of automated tools (AWS offers services to help with this) and a hopefully-somewhat-small userbase, I'm hoping that this can be doable as a one-man job to start.

> I'm imagining something like a Patreon to help defer recurring expenses

I hadn't considered that idea, but I like it. I don't _love_ the idea of charging money to users, but donations seem nice. I also know some folks who have been working on [Patch](https://bxcoding.org/patch/), a Scratch-Python synthesis project that is spiritually similar to Leopard, and [they were able to raise money](https://bxcoding.org/news/patch-wins-the-tufts-100k-new-ventures-competition/) for their work.

**Comment by towerofnix** [comment]
Hi, hi!

First and foremost: congrats ^_^ Getting to the point of having a conversation like this is obviously a big and essential step. And it's awesome to see that the no-way-no-how-definitely-not-complete editor is almost alpha-alpha-alpha ready :shipit: 🥳 

On a personal level—we (speaking as @towerofnix only: we're plural) have no problem with taking the relations we've shared as developers, feedback-offerers, and idea-supporting friends on sb-edit/leopard, and treating those relations as the grounds for the management, operation, and decision-making of the Leopard website.

Our prior experience with directing a project is (obviously) on [the Homestuck Music Wiki](https://hsmusic.wiki). It's a sort of interesting project in that it 1) naturally brings in quite a lot of people who are interested in helping, 2) is built—in all regards—on a measured mixture of making decisions that the community around the wiki agree with *and* following our own personal judgement, and 3) has no rigid interpersonal or inter-subproject structure and absolutely no definite "roles" within the community.

We'll touch on each of those points to give a better sense of where we're coming from. Some or none of this may be applicable to Leopard; since it's not our own project we can't really draw any connections, but figure you might make some while you read.

1. We're a wiki (niche) for music (niche) to do with Homestuck (niche). Put all three of those together and you'd think hardly anyone would take interest in visiting, let alone *helping,* but new people join our Discord and offer and find all different ways to help, on the regular!

    Socially—we're a concretely welcoming space, meaning we basically don't gatekeep over anything; we don't have strict terms for self-moderation (beyond basic server rules); and we foster a helpful and emotionally open environment, mainly by making the general air "chill" and being quick to address and pay caring attention to concerns of all sorts.

    The result of all this is a sort of common spirit that takes well to bringing new people in and making sure they feel welcomed and are genuinely respected and treated equal to anyone else. This has been absolutely essential in running the wiki for the reasons below, but also because we simply *need people* to make the wiki what it is! It'd be practically lifeless if it were one or maybe two people who cared about it and were part of work and conversations.

2. We're (as QN) inevitably "at the top" for a few different reasons: we're the only ones who code and design the wiki's software (which is a major part of its identity), we're responsible for everything to do with the web infrastructure (aka "keeping the site online" and "uploading updates"), we take care of general project management (including scope management for periodic updates, as well as a chunk of outreach and communication with folk outside the server), we created the wiki and we've held all these responsibilities for ~4 years, and so on.

    There's not really any getting around those realities, and they all put a certain degree of necessary decision-making leadership on us. For us, the way we've made ourselves comfortable with running the wiki (and holding those responsibilities) is by 1) accepting that we're on a practical pedestal for all those reasons, and 2) treating that placement with as much humility and openness as we reasonably can.

3. This is why the server and project as a whole have almost no hierarchy. A few trusted people have moderation permissions (which are limited to banning and deleting messages), but they aren't superficially differentiated from everyone else. We do our best to treat everyone equally and make sure all voices are heard, considered, and welcomed. We (personally) try to work with a lot of self-awareness: there are obviously ways we have experience that others don't, and that's important, but so does everyone *else* have a huge swathe of experience that *we* don't.

    We've generally found that arbitrary social ladders are pretty much the antithesis to the kind of environment that we want to foster for the wiki, so there's no such thing here. Still, we acknowledge the ways we have directional control over the project that others don't, and we're careful with and very open about the responsibilities we hold.

As regarding Leopard, we figure that whether or not you're in a similar position to us now (we'd say you are in a lot of ways, having created, creatively directed, and maintained the project, after all!)—you probably will be in a year or two! So, just some food for thought about our own experiences.

Again, we've got no personal problem at all with the direction and general relations you described. We just hope some of these values connect with you, and want you to know you're not alone, in any way at all, with the project you're about to start!

**Comment by PullJosh** [comment]
> First and foremost: congrats ^_^ Getting to the point of having a conversation like this is obviously a big and essential step. And it's awesome to see that the no-way-no-how-definitely-not-complete editor is almost alpha-alpha-alpha ready :shipit: 🥳

Thanks! The progress of Leopard is something for all of us to be proud of. Also, I am very glad to see that I've made the status of the editor crystal clear. 😉

> 1) accepting that we're on a practical pedestal for all those reasons, and 2) treating that placement with as much humility and openness as we reasonably can

Yes, perfect. This is 100% my intention. As a practical matter, I think it's helpful to have one person at the helm of a more centralized project like this (speaking of the website in contrast to the libraries), but day-to-day it should feel like the website is an expression of the community contained within it.

> We just hope some of these values connect with you, and want you to know you're not alone, in any way at all, with the project you're about to start!

😊
